"""Cut the real interchange announcement that follows each interchange station's "Next station, X".

SMRT lines: "Change at the next station for the <line(s)>".  SBS lines (NE, DT): "Passengers may alight
and change to the <line(s)>". Each is matched to the station whose "Next station" call it follows in the
same line recording, re-transcribed precisely, cut as one piece, cleaned, and written to
docs/audio/change/<CODE>-<slug>.mp3. Writes work/transfers_<LINE>.json and docs/transfers.js.

Usage: python tools/extract_transfers.py CC EW NS TE NE DT
"""
import glob, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, HERE)
import extract_online as X

OUT = os.path.join(ROOT, "docs", "audio", "change")
# station "Next station" start times added by hand later (not in work/extract_<LINE>.json)
EXTRA_STARTS = {"NS": {"NS1": ("Jurong East", 39.3)}, "EW": {"EW24": ("Jurong East", 730.6)}}
START = re.compile(r"^(change|passengers)$", re.I)
ENDWORDS = ("line", "lines", "lrt", "airport")
# transfer announcements that belong to a different station than the nearest earlier match
OVERRIDE = {"EW": {138.9: ("EW4", "Tanah Merah")}}


def station_starts(line):
    rep = json.load(open(os.path.join(ROOT, "work", f"extract_{line}.json"), encoding="utf-8"))
    out = [(v["start"], code, v["station"]) for code, v in rep.items()]
    out += [(t, code, st) for code, (st, t) in EXTRA_STARTS.get(line, {}).items()]
    return sorted(out)


def phrase_times(line):
    """Approximate start times of each transfer phrase in the (coarse) transcript."""
    hits = []
    for f in sorted(glob.glob(os.path.join(ROOT, "work", "transcripts", f"{line}*.json"))):
        for r in json.load(open(f, encoding="utf-8")):
            t = r["text"].lower()
            if re.search(r"change at the next station for|may (a ?light|alight|elite|align).{0,20}change to", t):
                w = next((w for w in r["words"] if re.match(r"(?i)\s*(change|passengers)", w[0])), None)
                hits.append(w[1] if w else r["start"])
    return sorted(set(round(h, 1) for h in hits))


def precise(line, t):
    """Re-transcribe around t; return (start, end, text) of the transfer sentence."""
    words = X.small_words_en(line, t - 6, t + 12)
    starts = [i for i, w in enumerate(words) if START.match(re.sub(r"[^A-Za-z]", "", w[0])) and w[1] <= t + 1.5]
    if not starts: return None
    k = min(starts, key=lambda i: abs(words[i][1] - t))
    j = k
    while j + 1 < len(words) and words[j + 1][1] - words[j][2] < .6:
        j += 1
        if re.sub(r"[^a-z]", "", words[j][0].lower()) in ENDWORDS and re.sub(r"[^a-z]", "", (words[j + 1][0] if j + 1 < len(words) else "").lower()) not in ("or", "and"):
            break
    text = " ".join(w[0] for w in words[k:j + 1])
    return words[k][1], words[j][2], text


def main():
    os.makedirs(OUT, exist_ok=True)
    if len(sys.argv) == 1: sys.argv.append("--index-only")
    table = {}
    for line in [a for a in sys.argv[1:] if not a.startswith("--")]:
        starts = station_starts(line)
        found = {}
        for t in phrase_times(line):
            prev = [s for s in starts if s[0] < t and t - s[0] < 25]
            if not prev: continue
            _, code, name = prev[-1]
            code, name = OVERRIDE.get(line, {}).get(t, (code, name))
            if code in found: continue          # keep the first, i.e. the "next station" one
            p = precise(line, t)
            if not p: continue
            a, b, text = p
            if "next station" not in text.lower() and "change to" not in text.lower() and "may" not in text.lower():
                continue                          # skip "change at THIS station"
            slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
            f = f"change/{code}-{slug}.mp3"
            X.render(line, [(a - .12, b + .25)], os.path.join(ROOT, "docs", "audio", f))
            found[code] = {"station": name, "file": f, "start": round(a, 2), "end": round(b, 2), "text": text}
            print(f"  {code:5s} {name:18s} {a:7.2f}-{b:7.2f}  {text}", flush=True)
        json.dump(found, open(os.path.join(ROOT, "work", f"transfers_{line}.json"), "w", encoding="utf-8"),
                  indent=1, ensure_ascii=False)
    # docs/transfers.js: code -> file, from every line processed so far
    # station clips that already say "...change to the ... line" themselves (one long piece): no extra clip
    inline = set(json.load(open(os.path.join(ROOT, "work", "inline_transfers.json"))))
    for f in glob.glob(os.path.join(ROOT, "work", "transfers_*.json")):
        for code, v in json.load(open(f, encoding="utf-8")).items():
            if code not in inline: table[code] = v["file"]
    with open(os.path.join(ROOT, "docs", "transfers.js"), "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/extract_transfers.py: real interchange announcement per station code.\n")
        fh.write("const TRANSFER_CLIPS = " + json.dumps(dict(sorted(table.items())), indent=1) + ";\n")


if __name__ == "__main__":
    main()
