"""Cut the extra on-board announcements (mind the gap, suspicious article, ...) in each language.

Times come from transcribing + language-detecting the online line recordings (see transcribe_online.py).
Each cut point is snapped to the quietest moment within +/-SNAP seconds so no word is clipped where one
language hands over to the next. Writes docs/audio/extras/<key>-<lang>.mp3 and docs/extras.js.

Usage: python tools/extract_extras.py
"""
import json, os, subprocess, sys
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, HERE)
import extract_online as X

SNAP = .12
# key: (label, icon, line, {lang: (start, end)})
EXTRAS = {
    "mind-gap":  ("Please mind the gap", "gap", "NE",
                  {"en": (178.78, 180.27), "zh": (180.3, 182.12), "ms": (182.2, 184.45), "ta": (184.55, 188.78)}),
    "no-lean":   ("Please do not lean against the train doors", "lean", "CC", {"en": (83.3, 86.4)}),
    "centre":    ("Please move to the centre of the car", "centre", "NE", {"en": (27.45, 37.2)}),
    "belongings": ("Please do not leave your belongings unattended", "bag", "DT",
                  {"en": (136.47, 151.5), "zh": (151.55, 168.53), "ms": (168.53, 183.91), "ta": (183.91, 202.03)}),
    "track":     ("Track crossing ahead, please hold on", "track", "EW", {"en": (94.35, 100.0)}),
}


def snap(line, t):
    """Quietest 20 ms frame within +/-SNAP s of t."""
    x = X.audio16(line)
    a, b = int((t - SNAP) * 16000), int((t + SNAP) * 16000)
    h = 320
    frames = [np.sqrt(np.mean(x[i:i + h] ** 2)) for i in range(max(0, a), b - h, h)]
    return max(0, a) / 16000 + int(np.argmin(frames)) * h / 16000 + .01


def main():
    out_dir = os.path.join(ROOT, "docs", "audio", "extras")
    os.makedirs(out_dir, exist_ok=True)
    table = {}
    for key, (label, icon, line, versions) in EXTRAS.items():
        table[key] = {"label": label, "icon": icon, "files": {}}
        for lang, (a, b) in versions.items():
            a2, b2 = snap(line, a), snap(line, b)
            name = f"{key}-{lang}.mp3"
            X.render(line, [(a2, b2)], os.path.join(out_dir, name))
            table[key]["files"][lang] = f"extras/{name}"
            print(f"{key:11s} {lang}  {a2:7.2f}-{b2:7.2f}s  ({b2 - a2:.1f}s)", flush=True)
    with open(os.path.join(ROOT, "docs", "extras.js"), "w", encoding="utf-8") as f:
        f.write("// Generated by tools/extract_extras.py: extra on-board announcements, per language.\n")
        f.write("const EXTRAS = " + json.dumps(table, indent=1, ensure_ascii=False) + ";\n")


if __name__ == "__main__":
    main()
