"""Write docs/next.js: station -> real "Next station" clip, preferring the station's first listed line.

Usage: python tools/make_next_index.py
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, HERE)
from extract_online import network

files = {f.split("-")[0]: f for f in os.listdir(os.path.join(ROOT, "docs", "audio", "next")) if f.endswith(".mp3")}
codes = {}
for line, stops in network().items():
    for code, name in stops:
        codes.setdefault(name, []).append(code)
# network.js lists lines NS, EW, CG, NE, CC, CE, DT, TE: that order decides the "first listed" line
# interchange announcements we have (and stations whose clip already says it)
tf = os.path.join(ROOT, "docs", "transfers.js")
transfers = set(json.loads(open(tf, encoding="utf-8").read().split("=", 1)[1].strip().rstrip(";"))) if os.path.exists(tf) else set()
inline_f = os.path.join(ROOT, "work", "inline_transfers.json")
transfers |= set(json.load(open(inline_f))) if os.path.exists(inline_f) else set()
# hand-picked line for a station (e.g. its only clean clip that already includes the change message)
PREFER = {"Outram Park": "TE17"}
clips = {}
for name, cs in codes.items():
    have = [c for c in cs if c in files]
    if not have: continue
    # interchanges: prefer a line whose recording also has the change announcement, so both parts
    # play in the same voice; otherwise the first listed line
    pick = next((c for c in have if c in transfers), have[0]) if len(cs) > 1 else have[0]
    pick = PREFER.get(name) if PREFER.get(name) in have else pick
    clips[name] = "next/" + files[pick]
missing = sorted(n for n in codes if n not in clips)
with open(os.path.join(ROOT, "docs", "next.js"), "w", encoding="utf-8") as f:
    f.write("// Generated by tools/make_next_index.py: real on-board \"Next station\" announcement per station.\n")
    f.write("const NEXT_CLIPS = " + json.dumps(clips, indent=1, ensure_ascii=False) + ";\n")
print(f"{len(clips)} stations have a real clip; {len(missing)} without: {', '.join(missing)}")
