"""Generate a spoken-name clip for every MRT station, in the voice matched to the real announcer.

Each clip = the real arrival chime (cleaned) + the station name, tone-matched to the announcer
with the EQ filter from tools/eq_match.py.

Usage: python tools/make_names.py [--only "Farrer Road,Bugis"] [--voice en-PH-RosaNeural --rate -12 --pitch 8]
Writes docs/audio/names/<slug>.mp3 and docs/names.js (station -> file map for the page).
"""
import argparse, asyncio, json, os, re, subprocess, sys, tempfile
import numpy as np, soundfile as sf, librosa, edge_tts
from scipy.signal import lfilter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, HERE)
from clean import clean
from cut import trim, fade, CHIME_SRC, CHIME_AT, CHIME_NOISE
from eq_match import build as build_eq, WORK

SR = 48000
OUT = os.path.join(ROOT, "docs", "audio", "names")


def stations():
    """Read station names from site/network.js (the ST table)."""
    js = open(os.path.join(ROOT, "docs", "network.js"), encoding="utf-8").read()
    body = js[js.index("const ST"):js.index("};", js.index("const ST"))]
    return re.findall(r'"([^"]+)":\s*\[', body)


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--only")
    ap.add_argument("--voice", default="en-PH-RosaNeural")
    ap.add_argument("--rate", type=int, default=-12)
    ap.add_argument("--pitch", type=int, default=8)
    a = ap.parse_args()

    os.makedirs(OUT, exist_ok=True)
    taps = build_eq(a.voice, a.rate, a.pitch)       # tone-match filter for these exact settings
    say_as = json.load(open(os.path.join(HERE, "pronunciation.json"), encoding="utf-8"))
    chime = fade(trim(clean(CHIME_SRC, *CHIME_AT, CHIME_NOISE)))

    names = stations()
    todo = a.only.split(",") if a.only else names
    with tempfile.TemporaryDirectory() as d:
        for name in todo:
            text = say_as.get(name, name) + "."
            raw = os.path.join(d, "raw.mp3")
            asyncio.run(edge_tts.Communicate(text, a.voice, rate=f"{a.rate:+d}%", pitch=f"{a.pitch:+d}Hz").save(raw))
            y, _ = librosa.load(raw, sr=SR, mono=True)
            y = librosa.effects.trim(y, top_db=35)[0]
            y = lfilter(taps, 1, np.concatenate([y, np.zeros(len(taps))]))[len(taps) // 2:len(taps) // 2 + len(y)]
            y = fade(y / (np.abs(y).max() + 1e-9) * .8)
            clip = np.concatenate([chime / (np.abs(chime).max() + 1e-9) * .6, np.zeros(int(.3 * SR)), y])
            wav = os.path.join(d, "x.wav")
            sf.write(wav, clip, SR)
            out = os.path.join(OUT, slug(name) + ".mp3")
            subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", wav, "-af", "highpass=f=120,loudnorm=I=-16:TP=-1.5",
                            "-ar", "48000", "-ac", "1", "-b:a", "96k", out], check=True)
            print("ok", name, flush=True)

    with open(os.path.join(ROOT, "docs", "names.js"), "w", encoding="utf-8") as f:
        f.write("// Generated by tools/make_names.py: spoken station names (voice matched to the announcer).\n")
        f.write("const NAME_CLIPS = " + json.dumps({n: f"names/{slug(n)}.mp3" for n in names}, indent=1) + ";\n")


if __name__ == "__main__":
    main()
