"""Write docs/next.js: station -> real "Next station" clip, preferring the station's first listed line.

Usage: python tools/make_next_index.py
"""
import json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, "..")
sys.path.insert(0, HERE)
from extract_online import network

files = {f.split("-")[0]: f for f in os.listdir(os.path.join(ROOT, "docs", "audio", "next")) if f.endswith(".mp3")}
codes = {}
for line, stops in network().items():
    for code, name in stops:
        codes.setdefault(name, []).append(code)
# network.js lists lines NS, EW, CG, NE, CC, CE, DT, TE: that order decides the "first listed" line
clips = {}
for name, cs in codes.items():
    hit = next((files[c] for c in cs if c in files), None)
    if hit: clips[name] = "next/" + hit
missing = sorted(n for n in codes if n not in clips)
with open(os.path.join(ROOT, "docs", "next.js"), "w", encoding="utf-8") as f:
    f.write("// Generated by tools/make_next_index.py: real on-board \"Next station\" announcement per station.\n")
    f.write("const NEXT_CLIPS = " + json.dumps(clips, indent=1, ensure_ascii=False) + ";\n")
print(f"{len(clips)} stations have a real clip; {len(missing)} without: {', '.join(missing)}")
